import { kb, pct } from '../ci/budgets.ts'
import type { Budgets, Snapshot } from '../store/snapshot.ts'

/** Headroom over the current worst route, so day one is green and only new weight fails. */
const HEADROOM = 1.1
const BYTE_STEP = 10_000
/** Slack under the lowest measured shell, for the same reason. */
const SHELL_SLACK = 0.1
const SHELL_STEP = 0.05
/** Not derived from anything - see the note it carries. */
const START_MAX_GROWTH = 0.05

export interface AnnotatedBudgets extends Budgets {
  /**
   * How every number below was arrived at. JSON has no comments and `readBudgets`
   * ignores unknown keys, so this is the only place the derivation can sit next to
   * the numbers - and a threshold nobody can explain in review is one nobody edits.
   */
  '//': string[]
}

export interface StarterBudgets {
  budgets: AnnotatedBudgets
  /** The same lines, for the terminal report. */
  notes: string[]
}

/**
 * Starter ceilings from one build. The notes keep two kinds of number apart:
 * *derived* ones restate what this build measures, *chosen* ones are crust's
 * opinion, and presenting the second as evidence is how a generated file becomes
 * an unquestionable standard.
 *
 * Null when no route has a size - an empty budget file only pretends to have
 * ceilings.
 */
export function deriveStarterBudgets(snapshot: Snapshot): StarterBudgets | null {
  const sized = snapshot.routes.filter((route) => route.firstLoadBytes > 0)
  if (sized.length === 0) return null

  const heaviest = sized.reduce((a, b) => (b.firstLoadBytes > a.firstLoadBytes ? b : a))
  const firstLoadCeiling = roundUpTo(heaviest.firstLoadBytes * HEADROOM, BYTE_STEP)

  const notes = [
    `Generated by crust init from build ${snapshot.buildId} (${snapshot.routes.length} routes, Next ${snapshot.nextVersion}, ${snapshot.bundler}).`,
    'Derived from one build, so they describe today rather than a standard. Review every number before committing it.',
    `defaultFirstLoadBytes ${firstLoadCeiling} (${kb(firstLoadCeiling)}) - derived: the heaviest route (${heaviest.pattern}) is ${kb(heaviest.firstLoadBytes)}, plus 10% headroom, rounded up to the next 10 kB. Nothing in this build breaches it.`,
    `maxGrowth ${pct(START_MAX_GROWTH)} - chosen, not measured: crust has one build and cannot know how fast this app grows on purpose. It fails a route that grows faster than this against its baseline.`,
    'No per-route firstLoadBytes entries - crust cannot know which routes deserve a tighter ceiling than the rest. Add them yourself: "firstLoadBytes": { "/checkout": 180000 }.',
  ]

  const measured = sized
    .map((route) => ({ route, ratio: route.shell?.actual?.shellRatio }))
    .filter((entry): entry is { route: (typeof sized)[number]; ratio: number } => typeof entry.ratio === 'number')

  let minShellRatio: number | undefined
  if (measured.length === 0) {
    notes.push(
      'No shell floor - no route in this build emitted a static shell crust could measure, so there is nothing to derive one from. A route that stops emitting a shell still fails, with no number needed.',
    )
  } else {
    const lowest = measured.reduce((a, b) => (b.ratio < a.ratio ? b : a))
    const floor = floorTo(lowest.ratio - SHELL_SLACK, SHELL_STEP)
    if (floor <= 0) {
      notes.push(
        `No shell floor - the lowest measured shell is already ${pct(lowest.ratio)} (${lowest.route.pattern}), too low to floor without failing the build it was derived from.`,
      )
    } else {
      minShellRatio = floor
      notes.push(
        `defaultMinShellRatio ${floor} (${pct(floor)}) - derived: the lowest measured shell is ${pct(lowest.ratio)} (${lowest.route.pattern}), floored 10 points below it.`,
      )
    }
  }

  notes.push(
    'No allowRegression list - rendering-mode drops, reads that stopped being cached, and a vanished shell fail with no thresholds at all. Name a route here only when the downgrade was the point of the change.',
  )

  return {
    notes,
    budgets: {
      '//': notes,
      defaultFirstLoadBytes: firstLoadCeiling,
      maxGrowth: START_MAX_GROWTH,
      ...(minShellRatio === undefined ? {} : { defaultMinShellRatio: minShellRatio }),
    },
  }
}

/** The rules that need no budget file, for the report to state rather than imply. */
export const ZERO_CONFIG_RULES = [
  'a route became less static (static -> partial, static -> isr, anything -> dynamic)',
  'a read that was cached stopped being cached',
  'a route that emitted a static shell stopped emitting one',
] as const

const roundUpTo = (value: number, step: number): number => Math.ceil(value / step) * step

const floorTo = (value: number, step: number): number => {
  // Both roundings matter. `0.35 / 0.05` is 6.999… in binary floating point, so
  // flooring it raw turns a 30% floor into 35%; and `7 * 0.05` is
  // 0.35000000000000003, which would be written into the file verbatim.
  const steps = Math.floor(Number((value / step).toFixed(6)))
  return Number((steps * step).toFixed(4))
}
