import type { CiProvider, NextApp, PackageManager } from './detect.ts'

export interface CiConfigInput {
  provider: CiProvider
  /** Pinned into the generated config - the version that computes the verdict. */
  toolVersion: string
  packageManager: PackageManager
  /** From the root `packageManager` field, when it agrees with the lockfile. */
  packageManagerVersion?: string | null
  app: NextApp
  distDir: string
  baseline: string
  nodeMajor: number
}

export interface CiConfigFile {
  /** Workspace-relative path to write. */
  path: string
  contents: string
  /**
   * A `workflow` runs as written. A `snippet` cannot: GitLab and CircleCI keep
   * the whole pipeline in one file, and appending to a file the project already
   * maintains is how a setup command breaks a working pipeline.
   */
  kind: 'workflow' | 'snippet'
}

export function ciConfigFor(input: CiConfigInput): CiConfigFile {
  if (input.provider === 'github') {
    return { path: '.github/workflows/crust.yml', contents: githubWorkflow(input), kind: 'workflow' }
  }
  if (input.provider === 'gitlab') {
    return { path: '.perf/ci/gitlab-ci.crust.yml', contents: gitlabJob(input), kind: 'snippet' }
  }
  return { path: '.perf/ci/circleci.crust.yml', contents: circleciJob(input), kind: 'snippet' }
}

const INSTALL: Record<PackageManager, string> = {
  pnpm: 'pnpm install --frozen-lockfile',
  yarn: 'yarn install --immutable',
  npm: 'npm ci',
  bun: 'bun install --frozen-lockfile',
}

function githubWorkflow(input: CiConfigInput): string {
  const pkg = pinned(input.toolVersion)
  const inApp = input.app.relativeDir !== '.'
  const lines: string[] = [
    `# Generated by crust init ${input.toolVersion}.`,
    '#',
    `# The verdict comes from ${pkg}, pinned so a crust release cannot`,
    '# change your check without a commit here. The action is the plumbing around it:',
    '# fetch history, run the check, publish the snapshot, post one comment. Point it at',
    '# a release tag instead of @master when you want that frozen too.',
    'name: crust',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    // The baseline branch has to build too: a pull request compares against the
    // merge base, and nothing recorded it if the branch never ran the workflow.
    `    branches: [${input.baseline}]`,
    '',
    'permissions:',
    '  contents: write        # publish snapshots to the perf-history branch',
    '  pull-requests: write   # post the report comment',
    '',
    'jobs:',
    '  crust:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
  ]

  if (input.packageManager === 'pnpm') {
    lines.push('      - uses: pnpm/action-setup@v4')
    // With no version input the action reads `packageManager` from package.json,
    // which is one fewer number to keep in step with the lockfile.
    if (input.packageManagerVersion) lines.push('        # version comes from package.json packageManager')
    else lines.push('        with:', '          version: 10')
  }
  if (input.packageManager === 'bun') {
    lines.push('      - uses: oven-sh/setup-bun@v2')
  }

  lines.push('      - uses: actions/setup-node@v4', '        with:', `          node-version: ${input.nodeMajor}`)
  // setup-node caches npm, yarn and pnpm; it has no bun mode, and naming one
  // fails the step rather than skipping the cache.
  if (input.packageManager !== 'bun') lines.push(`          cache: ${input.packageManager}`)

  lines.push(`      - run: ${INSTALL[input.packageManager]}`)
  lines.push('      - name: Build the app', `        run: ${buildCommand(input)}`)
  // crust reads what the build emitted, so the build runs where the app is.
  if (inApp) lines.push(`        working-directory: ${input.app.relativeDir}`)

  lines.push(
    // `master` is the branch this action actually lives on. `@main` resolved to
    // nothing, so every generated workflow failed on "unable to resolve action"
    // before it ran a single step.
    '      - uses: moumen-soliman/crust/action@master',
    '        with:',
    `          crust-version: ${input.toolVersion}`,
    `          baseline: ${input.baseline}`,
  )
  if (inApp) lines.push(`          working-directory: ${input.app.relativeDir}`)
  if (input.distDir !== '.next') lines.push(`          dist-dir: ${input.distDir}`)

  return lines.join('\n') + '\n'
}

function gitlabJob(input: CiConfigInput): string {
  const pkg = pinned(input.toolVersion)
  const lines: string[] = [
    `# Generated by crust init ${input.toolVersion} - add this job to .gitlab-ci.yml.`,
    '#',
    `# Pinned to ${pkg}. \`--comment\` only writes the Markdown; posting it is`,
    '# GitLab\'s job, so it is kept as an artifact you can attach to the merge request.',
    'crust:',
    `  image: node:${input.nodeMajor}`,
    '  rules:',
    '    - if: $CI_PIPELINE_SOURCE == "merge_request_event"',
    `    - if: $CI_COMMIT_BRANCH == "${input.baseline}"`,
    '  script:',
  ]

  if (input.packageManager === 'pnpm' || input.packageManager === 'yarn') {
    lines.push('    - corepack enable')
  }
  if (input.packageManager === 'bun') {
    lines.push('    - npm install --global bun')
  }

  lines.push(
    `    - ${INSTALL[input.packageManager]}`,
    `    - ${cdPrefix(input)}${buildCommand(input)}`,
    // A fresh clone has no .perf/, so the orphan branch is the only baseline. It
    // is allowed to fail: a first run has nothing to fetch.
    `    - npx --yes ${pkg} history fetch${cwdFlag(input)} || true`,
    `    - npx --yes ${pkg} ci ${input.baseline}${cwdFlag(input)}${distFlag(input)} --comment crust-comment.md`,
    `    - npx --yes ${pkg} history push${cwdFlag(input)} || true`,
    '  artifacts:',
    '    when: always',
    '    paths:',
    '      - crust-comment.md',
  )

  return lines.join('\n') + '\n'
}

function circleciJob(input: CiConfigInput): string {
  const pkg = pinned(input.toolVersion)
  const lines: string[] = [
    `# Generated by crust init ${input.toolVersion} - merge this into .circleci/config.yml`,
    '# under the existing `jobs:` and `workflows:` keys.',
    '#',
    `# Pinned to ${pkg}. The comment is stored as an artifact; posting it to the`,
    '# pull request is CircleCI\'s job.',
    'jobs:',
    '  crust:',
    '    docker:',
    `      - image: cimg/node:${input.nodeMajor}.0`,
    '    steps:',
    '      - checkout',
  ]

  if (input.packageManager === 'pnpm' || input.packageManager === 'yarn') {
    lines.push('      - run: corepack enable')
  }
  if (input.packageManager === 'bun') {
    lines.push('      - run: npm install --global bun')
  }

  lines.push(
    `      - run: ${INSTALL[input.packageManager]}`,
    `      - run: ${cdPrefix(input)}${buildCommand(input)}`,
    `      - run: npx --yes ${pkg} history fetch${cwdFlag(input)} || true`,
    `      - run: npx --yes ${pkg} ci ${input.baseline}${cwdFlag(input)}${distFlag(input)} --comment crust-comment.md`,
    `      - run: npx --yes ${pkg} history push${cwdFlag(input)} || true`,
    '      - store_artifacts:',
    '          path: crust-comment.md',
    '',
    'workflows:',
    '  crust:',
    '    jobs:',
    '      - crust',
  )

  return lines.join('\n') + '\n'
}

const pinned = (toolVersion: string): string => `@moumensoliman/crust@${toolVersion}`

const RUN: Record<PackageManager, string> = {
  pnpm: 'pnpm run build',
  yarn: 'yarn run build',
  npm: 'npm run build',
  bun: 'bun run build',
}

/**
 * The project's own build script when it has one - it may set env, flags or a
 * turbo filter that `next build` alone does not - and `next build` when it does
 * not, because crust needs a production build to exist either way.
 */
const buildCommand = (input: CiConfigInput): string =>
  input.app.hasBuildScript ? RUN[input.packageManager] : 'npx --yes next build'

const cdPrefix = (input: CiConfigInput): string =>
  input.app.relativeDir === '.' ? '' : `cd ${input.app.relativeDir} && `

const cwdFlag = (input: CiConfigInput): string =>
  input.app.relativeDir === '.' ? '' : ` --cwd ${input.app.relativeDir}`

const distFlag = (input: CiConfigInput): string =>
  input.distDir === '.next' ? '' : ` --dist-dir ${input.distDir}`
